name: lorem_gen
description: A simple and lite `Dart` package to generate Lorem (Ipsum) and populate your app with random generated text.
version: 2.0.0
repository: https://github.com/belachkar/lorem_gen
issue_tracker: https://github.com/belachkar/lorem_gen/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
