name: lorem_gen
description: A simple lorem ipsum text generator. Based on lipsum-dart package.
version: 1.0.0
homepage: https://github.com/belachkar/lorem_gen
publish_to: https://pub.dev/packages/lorem_gen

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
