name: lorem_gen
description: A simple and lite package to generate Lorem Ipsum and populate your app with text.
version: 1.0.2
homepage: https://github.com/belachkar/flutter_pkg_lorem_gen

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
