name: Dart CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    # use the google/dart container (this makes `dart` available to use)
    # container:
    #   image: google/dart:latest

    # checkout the code, run pub get and finally run tests
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@main
        with:
          channel: "stable"

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test
